# Generated by Django 4.1.4 on 2022-12-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=255)),
                ('triggered', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('description', models.CharField(choices=[('DevOps Escalation', 'Devops Escalation'), ('Security Ops Escalation', 'Security Ops Escalation')], default='DevOps Escalation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['id'],
            },
        ),
    ]
