# Generated by Django 4.1.4 on 2022-12-25 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('oncall', models.BooleanField(default=False)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('incidents', models.ManyToManyField(blank=True, to='incidents.incidents')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['id'],
            },
        ),
    ]
