# Generated by Django 4.1.4 on 2022-12-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
