# Generated by Django 4.1.4 on 2024-11-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('occurence_count', models.PositiveIntegerField(default=1)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
                'unique_together': {('host',)},
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On Call Schedule',
                'verbose_name_plural': 'On Call Schedules',
                'ordering': ['start_time'],
                'unique_together': {('team', 'user', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'CRITICAL'), (3, 'UNKNOWN'), (4, 'DOWN'), (5, 'UNREACHABLE')], default=0, max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(choices=[('DevOps Escalation', 'Devops Escalation'), ('Security Ops Escalation', 'Security Ops Escalation'), ('Performance Ops Escalation', 'Performance Ops Escalation'), ('Breakdown Ops Escalation', 'Breakdown Ops Escalation')], default='DevOps Escalation', max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.team')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['id'],
                'unique_together': {('team', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalation',
                'verbose_name_plural': 'Escalations',
                'ordering': ['level'],
                'unique_together': {('team', 'level', 'user')},
            },
        ),
    ]
