# Generated by Django 4.1.4 on 2023-04-16 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidents',
            name='statut',
            field=models.CharField(choices=[(0, 'In progress'), (1, 'Resolved'), (2, 'Closed')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.CharField(choices=[('DevOps Escalation', 'Devops Escalation'), ('Security Ops Escalation', 'Security Ops Escalation'), ('Performance Ops Escalation', 'Performance Ops Escalation'), ('Breakdown Ops Escalation', 'Breakdown Ops Escalation')], default='DevOps Escalation', max_length=255),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('phone_number', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidents')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidents')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-id'],
            },
        ),
    ]
