# Generated by Django 4.1.4 on 2024-08-28 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_rename_phone_number_notification_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='incidents',
            name='statut',
            field=models.CharField(choices=[(0, 'In progress'), (1, 'Resolved'), (2, 'Closed'), (3, 'Pending'), (4, 'Investigating'), (5, 'Remediated'), (6, 'Out of Scope'), (7, 'Deferred'), (8, 'Canceled'), (9, 'Reopened')], default=0, max_length=1),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('check_command', models.CharField(max_length=255)),
                ('check_interval', models.PositiveIntegerField()),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(0, 'In progress'), (1, 'Resolved'), (2, 'Closed'), (3, 'Pending'), (4, 'Investigating'), (5, 'Remediated'), (6, 'Out of Scope'), (7, 'Deferred'), (8, 'Canceled'), (9, 'Reopened')], default=3, max_length=1)),
                ('last_output', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.host')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
    ]
