# Generated by Django 4.1.4 on 2024-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_host_created_at_host_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'CRITICAL'), (3, 'UNKNOWN'), (4, 'DOWN'), (5, 'UNREACHABLE')], default=0, max_length=1),
        ),
    ]
